[workspace]
members = [
    "control-core",
    "control-hub", 
    # "control-hub-macros",
    # "control-run",
]
resolver = "2"

[workspace.dependencies]
qitech_lib = { git = "https://github.com/qitechgmbh/qitech_lib.git", rev="657ca9a2a89c928108626d12bb7476dab4071dbe" }
serde = { version = "1.0.217", default-features = false, features = ["derive"]}
tokio = { version = "1", features = ["full"] }
chrono= { version = "0.4.45", features = ["serde"]}
anyhow = "1.0.103"

indexmap = { version = "2", default-features = false, features = ["serde"] }
serde_json = "1.0.150"