[workspace]
members = [
    "examples/minimal_machines/*", 
    "examples/concepts/*",
    "core",
    "macros",
    "library",
    # "hub",
    "tui",
    "minimal"
]
resolver = "2"

[workspace.package]
repository = "https://github.com/qitechgmbh/qitech_framework"
keywords = ["ethercat", "machine", "tui"]
categories = [""]
license = "LGPL-3.0-only"
exclude = [".github", ".vscode"]
edition = "2024"
rust-version = "1.90"

[workspace.dependencies]
qitech_lib = { git = "https://github.com/qitechgmbh/qitech_lib.git", rev="530355c00baf6335f6085441c2a497d9ac060af6" }

serde = { version = "1.0.217", default-features = false, features = ["derive"]}
tokio = { version = "1", features = ["full"] }
chrono= { version = "0.4.45", features = ["serde"]}
anyhow = "1.0.103"
thiserror = "2.0.19"

futures = { version = "0.3.33", features = ["std"] }

indexmap = { version = "2", default-features = false, features = ["serde"] }
serde_json = "1.0.150"
yaml_serde = { version = "0.10.4", default-features = false }

tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }