[package]
name = "debug"
version = "0.1.0"
edition = "2024"

[dependencies]
qitech_lib.workspace = true
qitech_framework.workspace = true
qitech_framework_hub.workspace = true
qitech_framework_core.workspace = true

tracing.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing-subscriber.workspace = true
async-trait = "0.1.92"
socketioxide = { version = "0.18.6", features = ["msgpack"] }
tower-http = { workspace = true ,features = ["cors","trace"] } 
arc-swap.workspace = true
