[package]
name = "control_hub"
version = "0.1.0"
edition = "2024"

[dependencies]
# --- internal deps ---
control_core = { path = "../control-core" }

# --- workspace deps ---
anyhow = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
indexmap = { workspace = true }

# --- unique deps ---

# parsing
serde_json = "1.0.150"

# database
clickhouse = { version = "0.15.1", features = ["inserter", "chrono"] }

# networking
tower-http = { version = "0.6.8", features = ["cors","trace"] }
axum = "0.8"

# async
tokio-util = "0.7.18"
futures = "0.3.32"

# misc
arc-swap = "1.9.2"
tracing = "0.1.44"
