[package]
name = "qitech_framework_hub"
version = "0.1.0"
edition = "2024"

[dependencies]
# --- internal deps ---
qitech_framework_core.workspace = true

# --- external deps ---
arc-swap.workspace = true
chrono.workspace = true
indexmap.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true

# # database
# clickhouse = { workspace = true, features = ["inserter", "chrono"] }

# [dev-dependencies]
# qitech_lib.workspace = true
# qitech_framework.workspace = true
# testcontainers = { workspace = true, features = ["http_wait_plain"]}
# tracing.workspace = true
